---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhi.
--- DateTime: 2022/9/26 18:59
---


local Redis = require('redis')
local params = {
    host='redis.ops.lizhi.fm',
    port=6379
}

local redisClient = Redis.connect(params)
--redis:auth("xxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
local agents = redisClient:get("agent:LUDO_GAME")
print("agents",agents)


--ludo_game_info = client:get('LUDO_GAME')
--print(ludo_game_info)



--local zaddResult = redis.call('zadd', KEYS[1], ARGV[1], ARGV[2])
--     if (type(zaddResult) ~= 'nil' and zaddResult >= 0) then
--         redis.call('setex', KEYS[2], ARGV[3], ARGV[4]);
--     return 'OK';
--else
--     return 'FAIL';
--end